CREATE TABLE user_content_tag
(
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    user_id         NUMBER(19)                                                               NOT NULL,
    content_id      NUMBER(19)                                                               NOT NULL,
    name            VARCHAR2(80)                                                             NOT NULL,
    normalized_name VARCHAR2(80)                                                             NOT NULL,
    created_at      TIMESTAMP                                                                NOT NULL,

    CONSTRAINT pk_user_content_tag PRIMARY KEY (id),

    CONSTRAINT fk_user_content_tag_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_user_content_tag_content
        FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE,

    CONSTRAINT uk_user_content_tag_user_content_name
        UNIQUE (user_id, content_id, normalized_name)
);

CREATE INDEX idx_user_content_tag_user
    ON user_content_tag (user_id);

CREATE INDEX idx_user_content_tag_user_name
    ON user_content_tag (user_id, normalized_name);

CREATE INDEX idx_user_content_tag_user_content
    ON user_content_tag (user_id, content_id);