CREATE TABLE content_chunk
(
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    content_id NUMBER(19) NOT NULL,
    position   Integer,
    text       CLOB       NOT NULL,
    embedding  VECTOR(768, FLOAT32),

    CONSTRAINT pk_content_chunk PRIMARY KEY (id),

    CONSTRAINT fk_content_chunk_content
        FOREIGN KEY (content_id) REFERENCES content (id) ON DELETE CASCADE
);

CREATE INDEX idx_content_chunk_content
    ON content_chunk (content_id);